export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_LIST_SUCCESS: 'NOTE_LIST_SUCCESS',
    NOTE_LIST_FAIL: 'NOTE_LIST_FAIL',
    NOTE_DETAIL: 'NOTE_DETAIL',
    NOTE_DETAIL_SUCCESS: 'NOTE_DETAIL_SUCCESS',
    NOTE_DETAIL_FAIL: 'NOTE_DETAIL_FAIL',
    USER_LOCAL_TOKEN_SUCCESS: 'USER_LOCAL_TOKEN_SUCCESS',
    USER_LOCAL_TOKEN_FAIL: 'USER_LOCAL_TOKEN_FAIL',
    USER_CREATE_BLANK_USER_SUCCESS: 'USER_CREATE_BLANK_USER_SUCCESS',
    USER_CREATE_BLANK_USER_FAIL: 'USER_CREATE_BLANK_USER_FAIL',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    RSA_GET_SUCCESS: 'RSA_GET_SUCCESS',
    RSA_GET_FAIL: 'RSA_GET_FAIL'

}