export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    NOTE_LIST: 'NOTE_LIST',
    NOTE_LIST_SUCCESS: 'NOTE_LIST_SUCCESS',
    NOTE_LIST_FAIL: 'NOTE_LIST_FAIL',
    NOTE_DETAIL: 'NOTE_DETAIL',
    NOTE_DETAIL_SUCCESS: 'NOTE_DETAIL_SUCCESS',
    NOTE_DETAIL_FAIL: 'NOTE_DETAIL_FAIL'
}