export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    USER_LOCAL_TOKEN_SUCCESS: 'USER_LOCAL_TOKEN_SUCCESS',
    USER_LOCAL_TOKEN_FAIL: 'USER_LOCAL_TOKEN_FAIL',
    USER_CREATE_BLANK_USER_SUCCESS: 'USER_CREATE_BLANK_USER_SUCCESS',
    USER_CREATE_BLANK_USER_FAIL: 'USER_CREATE_BLANK_USER_FAIL',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL'
}